services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./apps/client/nginx.conf:/etc/nginx/conf.d/default.conf
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    platform: linux/amd64
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://admin:admin@database:5432/postgres?typeDefs=public
  database:
    container_name: database
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db:/var/lib/postgresql/data
  database-migrate:
    container_name: database-migrate
    build:
      context: .
      dockerfile: ./apps/database/migrate.dockerfile
    environment:
      - DATABASE_URL=postgres://admin:admin@database:5432/postgres?typeDefs=public
    volumes:
      - db:/var/lib/postgresql/data
    depends_on:
      - database
  database-seed:
    container_name: database-seed
    build:
      context: .
      dockerfile: ./apps/database/seed.dockerfile
    environment:
      - DATABASE_URL=postgres://admin:admin@database:5432/postgres?typeDefs=public
    volumes:
      - db:/var/lib/postgresql/data
    depends_on:
      - database-migrate
volumes:
  db:
    external: true
