export enum Subscription {
  MESSAGE_CREATED = "MESSAGE_CREATED",
  CONVERSATION_CREATED = "CONVERSATION_CREATED",
}

export enum Error {
  NOT_AUTHORIZED= "NOT_AUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
}
